spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/gymbook?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/   # 访问template下的html文件需要配置模板，映射
    suffix: .html
    mode: HTML
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ur.gymbook.model
# Mybatis基于注解开发，开启驼峰命名转换（否则为NULL）
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      ur:
        gymbook:
          mapper: debug



server:
  port: 8081
